const spacesData = [
  {
    "property_type": "Retail",
    "address": "1 146 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "Retail",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "1"
  },
  {
    "property_type": "Retail",
    "address": "1 146 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "2",
    "use_type": "Retail",
    "size_sf": "1919",
    "rent_per_sf": "$7.82",
    "page_number": "1"
  },
  {
    "property_type": "Retail",
    "address": "1 146 W 29th St",
    "city_state": "",
    "floor": "",
    "suite": "Retail",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$9.00",
    "page_number": "1"
  },
  {
    "property_type": "Retail",
    "address": "4 261 3rd Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "Corner",
    "use_type": "Retail",
    "size_sf": "700",
    "rent_per_sf": "Withheld",
    "page_number": "6"
  },
  {
    "property_type": "Retail",
    "address": "4 261 3rd Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1505",
    "rent_per_sf": "Withheld",
    "page_number": "6"
  },
  {
    "property_type": "Retail",
    "address": "4 261 3rd Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "117",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "6"
  },
  {
    "property_type": "Retail",
    "address": "4 261 3rd Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1690",
    "rent_per_sf": "Withheld",
    "page_number": "6"
  },
  {
    "property_type": "Retail",
    "address": "5 139 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1505",
    "rent_per_sf": "Withheld",
    "page_number": "7"
  },
  {
    "property_type": "Retail",
    "address": "5 139 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "117",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "7"
  },
  {
    "property_type": "Retail",
    "address": "5 139 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1690",
    "rent_per_sf": "Withheld",
    "page_number": "7"
  },
  {
    "property_type": "Retail",
    "address": "5 139 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "7"
  },
  {
    "property_type": "Retail",
    "address": "7 11 Penn Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1690",
    "rent_per_sf": "Withheld",
    "page_number": "10"
  },
  {
    "property_type": "Retail",
    "address": "7 11 Penn Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "10"
  },
  {
    "property_type": "Retail",
    "address": "7 11 Penn Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "1665",
    "rent_per_sf": "$8.75",
    "page_number": "10"
  },
  {
    "property_type": "Retail",
    "address": "8 311 Second Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "11"
  },
  {
    "property_type": "Retail",
    "address": "8 311 Second Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "1665",
    "rent_per_sf": "$8.75",
    "page_number": "11"
  },
  {
    "property_type": "Retail",
    "address": "9 146 W 4th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "1665",
    "rent_per_sf": "$8.75",
    "page_number": "13"
  },
  {
    "property_type": "Retail",
    "address": "9 146 W 4th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "Upper",
    "use_type": "Retail",
    "size_sf": "1520",
    "rent_per_sf": "$5.00",
    "page_number": "13"
  },
  {
    "property_type": "Retail",
    "address": "11 28 W 12th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "Upper",
    "use_type": "Retail",
    "size_sf": "1520",
    "rent_per_sf": "$5.00",
    "page_number": "17"
  },
  {
    "property_type": "Retail",
    "address": "11 28 W 12th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "1W",
    "use_type": "Retail",
    "size_sf": "1806",
    "rent_per_sf": "$8.31",
    "page_number": "17"
  },
  {
    "property_type": "Retail",
    "address": "11 28 W 12th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "$13.33",
    "page_number": "17"
  },
  {
    "property_type": "Retail",
    "address": "12 123 W 20th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "1W",
    "use_type": "Retail",
    "size_sf": "1806",
    "rent_per_sf": "$8.31",
    "page_number": "19"
  },
  {
    "property_type": "Retail",
    "address": "12 123 W 20th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "$13.33",
    "page_number": "19"
  },
  {
    "property_type": "Retail",
    "address": "12 123 W 20th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1000",
    "rent_per_sf": "$6.66",
    "page_number": "19"
  },
  {
    "property_type": "Retail",
    "address": "13 36 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "$13.33",
    "page_number": "21"
  },
  {
    "property_type": "Retail",
    "address": "13 36 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1000",
    "rent_per_sf": "$6.66",
    "page_number": "21"
  },
  {
    "property_type": "Retail",
    "address": "13 36 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1400",
    "rent_per_sf": "$5.76",
    "page_number": "21"
  },
  {
    "property_type": "Retail",
    "address": "15 150 W 26th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1400",
    "rent_per_sf": "$5.76",
    "page_number": "24"
  },
  {
    "property_type": "Retail",
    "address": "15 150 W 26th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1800",
    "rent_per_sf": "$8.08",
    "page_number": "24"
  },
  {
    "property_type": "Retail",
    "address": "15 150 W 26th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1050",
    "rent_per_sf": "$12.38",
    "page_number": "24"
  },
  {
    "property_type": "Retail",
    "address": "16 149 W 27th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1800",
    "rent_per_sf": "$8.08",
    "page_number": "26"
  },
  {
    "property_type": "Retail",
    "address": "16 149 W 27th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1050",
    "rent_per_sf": "$12.38",
    "page_number": "26"
  },
  {
    "property_type": "Retail",
    "address": "16 149 W 27th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "1806",
    "rent_per_sf": "Withheld",
    "page_number": "26"
  },
  {
    "property_type": "Retail",
    "address": "16 149 W 27th St",
    "city_state": "",
    "floor": "",
    "suite": "Space",
    "use_type": "Retail",
    "size_sf": "1335",
    "rent_per_sf": "Withheld",
    "page_number": "26"
  },
  {
    "property_type": "Retail",
    "address": "17 113 E 29th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1050",
    "rent_per_sf": "$12.38",
    "page_number": "27"
  },
  {
    "property_type": "Retail",
    "address": "17 113 E 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "1806",
    "rent_per_sf": "Withheld",
    "page_number": "27"
  },
  {
    "property_type": "Retail",
    "address": "17 113 E 29th St",
    "city_state": "",
    "floor": "",
    "suite": "Space",
    "use_type": "Retail",
    "size_sf": "1335",
    "rent_per_sf": "Withheld",
    "page_number": "27"
  },
  {
    "property_type": "Retail",
    "address": "17 113 E 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "$3.25",
    "page_number": "27"
  },
  {
    "property_type": "Retail",
    "address": "19 160 Bleecker St",
    "city_state": "",
    "floor": "",
    "suite": "Space",
    "use_type": "Retail",
    "size_sf": "1335",
    "rent_per_sf": "Withheld",
    "page_number": "30"
  },
  {
    "property_type": "Retail",
    "address": "19 160 Bleecker St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "$3.25",
    "page_number": "30"
  },
  {
    "property_type": "Retail",
    "address": "19 160 Bleecker St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$10.50",
    "page_number": "30"
  },
  {
    "property_type": "Retail",
    "address": "22 244 Eighth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$10.67",
    "page_number": "35"
  },
  {
    "property_type": "Retail",
    "address": "22 244 Eighth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "950",
    "rent_per_sf": "Withheld",
    "page_number": "35"
  },
  {
    "property_type": "Retail",
    "address": "22 244 Eighth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "800",
    "rent_per_sf": "$12.92",
    "page_number": "35"
  },
  {
    "property_type": "Retail",
    "address": "23 230 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "950",
    "rent_per_sf": "Withheld",
    "page_number": "37"
  },
  {
    "property_type": "Retail",
    "address": "23 230 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "800",
    "rent_per_sf": "$12.92",
    "page_number": "37"
  },
  {
    "property_type": "Retail",
    "address": "23 230 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$87.27",
    "page_number": "37"
  },
  {
    "property_type": "Retail",
    "address": "24 148 Madison Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "950",
    "rent_per_sf": "Withheld",
    "page_number": "39"
  },
  {
    "property_type": "Retail",
    "address": "24 148 Madison Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "800",
    "rent_per_sf": "$12.92",
    "page_number": "39"
  },
  {
    "property_type": "Retail",
    "address": "24 148 Madison Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$87.27",
    "page_number": "39"
  },
  {
    "property_type": "Retail",
    "address": "24 148 Madison Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$10.00",
    "page_number": "39"
  },
  {
    "property_type": "Retail",
    "address": "25 437 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "800",
    "rent_per_sf": "$12.92",
    "page_number": "40"
  },
  {
    "property_type": "Retail",
    "address": "25 437 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$87.27",
    "page_number": "40"
  },
  {
    "property_type": "Retail",
    "address": "25 437 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$10.00",
    "page_number": "40"
  },
  {
    "property_type": "Retail",
    "address": "26 133 Second Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$87.27",
    "page_number": "42"
  },
  {
    "property_type": "Retail",
    "address": "26 133 Second Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$10.00",
    "page_number": "42"
  },
  {
    "property_type": "Retail",
    "address": "27 5 St  Marks Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "$10.00",
    "page_number": "44"
  },
  {
    "property_type": "Retail",
    "address": "27 5 St  Marks Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1466",
    "rent_per_sf": "Withheld",
    "page_number": "44"
  },
  {
    "property_type": "Retail",
    "address": "29 85 4th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1466",
    "rent_per_sf": "Withheld",
    "page_number": "47"
  },
  {
    "property_type": "Retail",
    "address": "29 85 4th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "C",
    "use_type": "Retail",
    "size_sf": "1040",
    "rent_per_sf": "Withheld",
    "page_number": "47"
  },
  {
    "property_type": "Retail",
    "address": "29 85 4th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "D",
    "use_type": "Retail",
    "size_sf": "694",
    "rent_per_sf": "Withheld",
    "page_number": "47"
  },
  {
    "property_type": "Retail",
    "address": "29 85 4th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "B",
    "use_type": "Retail",
    "size_sf": "578",
    "rent_per_sf": "Withheld",
    "page_number": "47"
  },
  {
    "property_type": "Retail",
    "address": "29 85 4th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1785",
    "rent_per_sf": "Withheld",
    "page_number": "47"
  },
  {
    "property_type": "Retail",
    "address": "30 120 7th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "C",
    "use_type": "Retail",
    "size_sf": "1040",
    "rent_per_sf": "Withheld",
    "page_number": "49"
  },
  {
    "property_type": "Retail",
    "address": "30 120 7th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "D",
    "use_type": "Retail",
    "size_sf": "694",
    "rent_per_sf": "Withheld",
    "page_number": "49"
  },
  {
    "property_type": "Retail",
    "address": "30 120 7th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "B",
    "use_type": "Retail",
    "size_sf": "578",
    "rent_per_sf": "Withheld",
    "page_number": "49"
  },
  {
    "property_type": "Retail",
    "address": "30 120 7th Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1785",
    "rent_per_sf": "Withheld",
    "page_number": "49"
  },
  {
    "property_type": "Retail",
    "address": "30 120 7th Ave",
    "city_state": "",
    "floor": "",
    "suite": "21",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "49"
  },
  {
    "property_type": "Retail",
    "address": "33 60 E 8th St",
    "city_state": "",
    "floor": "",
    "suite": "747",
    "use_type": "Retail",
    "size_sf": "1250",
    "rent_per_sf": "Withheld",
    "page_number": "54"
  },
  {
    "property_type": "Retail",
    "address": "33 60 E 8th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "54"
  },
  {
    "property_type": "Retail",
    "address": "33 60 E 8th St",
    "city_state": "",
    "floor": "",
    "suite": "Commu-",
    "use_type": "Retail",
    "size_sf": "1027",
    "rent_per_sf": "Withheld",
    "page_number": "54"
  },
  {
    "property_type": "Retail",
    "address": "34 58 E 11th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "56"
  },
  {
    "property_type": "Retail",
    "address": "34 58 E 11th St",
    "city_state": "",
    "floor": "",
    "suite": "Commu-",
    "use_type": "Retail",
    "size_sf": "1027",
    "rent_per_sf": "Withheld",
    "page_number": "56"
  },
  {
    "property_type": "Retail",
    "address": "34 58 E 11th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1452",
    "rent_per_sf": "Withheld",
    "page_number": "56"
  },
  {
    "property_type": "Retail",
    "address": "35 21 E 12th St",
    "city_state": "",
    "floor": "",
    "suite": "Commu-",
    "use_type": "Retail",
    "size_sf": "1027",
    "rent_per_sf": "Withheld",
    "page_number": "57"
  },
  {
    "property_type": "Retail",
    "address": "35 21 E 12th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1452",
    "rent_per_sf": "Withheld",
    "page_number": "57"
  },
  {
    "property_type": "Retail",
    "address": "35 21 E 12th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1265",
    "rent_per_sf": "Withheld",
    "page_number": "57"
  },
  {
    "property_type": "Retail",
    "address": "35 21 E 12th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "B",
    "use_type": "Retail",
    "size_sf": "807",
    "rent_per_sf": "Withheld",
    "page_number": "57"
  },
  {
    "property_type": "Retail",
    "address": "38 212 W 14th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "63"
  },
  {
    "property_type": "Retail",
    "address": "38 212 W 14th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "63"
  },
  {
    "property_type": "Retail",
    "address": "38 212 W 14th St",
    "city_state": "",
    "floor": "",
    "suite": "555",
    "use_type": "Retail",
    "size_sf": "1290",
    "rent_per_sf": "Withheld",
    "page_number": "63"
  },
  {
    "property_type": "Retail",
    "address": "39 232 W 14th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "65"
  },
  {
    "property_type": "Retail",
    "address": "39 232 W 14th St",
    "city_state": "",
    "floor": "",
    "suite": "555",
    "use_type": "Retail",
    "size_sf": "1290",
    "rent_per_sf": "Withheld",
    "page_number": "65"
  },
  {
    "property_type": "Retail",
    "address": "39 232 W 14th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "Withheld",
    "page_number": "65"
  },
  {
    "property_type": "Retail",
    "address": "40 101 W 15th St",
    "city_state": "",
    "floor": "",
    "suite": "555",
    "use_type": "Retail",
    "size_sf": "1290",
    "rent_per_sf": "Withheld",
    "page_number": "67"
  },
  {
    "property_type": "Retail",
    "address": "40 101 W 15th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "Withheld",
    "page_number": "67"
  },
  {
    "property_type": "Retail",
    "address": "40 101 W 15th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1868",
    "rent_per_sf": "Withheld",
    "page_number": "67"
  },
  {
    "property_type": "Retail",
    "address": "41 17 E 17th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "Withheld",
    "page_number": "69"
  },
  {
    "property_type": "Retail",
    "address": "41 17 E 17th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1868",
    "rent_per_sf": "Withheld",
    "page_number": "69"
  },
  {
    "property_type": "Retail",
    "address": "41 17 E 17th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1098",
    "rent_per_sf": "Withheld",
    "page_number": "69"
  },
  {
    "property_type": "Retail",
    "address": "42 21 W 17th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1868",
    "rent_per_sf": "Withheld",
    "page_number": "70"
  },
  {
    "property_type": "Retail",
    "address": "42 21 W 17th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1098",
    "rent_per_sf": "Withheld",
    "page_number": "70"
  },
  {
    "property_type": "Retail",
    "address": "42 21 W 17th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "70"
  },
  {
    "property_type": "Retail",
    "address": "43 16 W 18th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1098",
    "rent_per_sf": "Withheld",
    "page_number": "72"
  },
  {
    "property_type": "Retail",
    "address": "43 16 W 18th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "72"
  },
  {
    "property_type": "Retail",
    "address": "44 200 E 20th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1098",
    "rent_per_sf": "Withheld",
    "page_number": "74"
  },
  {
    "property_type": "Retail",
    "address": "44 200 E 20th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "74"
  },
  {
    "property_type": "Retail",
    "address": "44 200 E 20th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "74"
  },
  {
    "property_type": "Retail",
    "address": "45 44 W 22nd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "75"
  },
  {
    "property_type": "Retail",
    "address": "45 44 W 22nd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "75"
  },
  {
    "property_type": "Retail",
    "address": "45 44 W 22nd St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "75"
  },
  {
    "property_type": "Retail",
    "address": "46 18 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "77"
  },
  {
    "property_type": "Retail",
    "address": "46 18 E 23rd St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "77"
  },
  {
    "property_type": "Retail",
    "address": "46 18 E 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "Withheld",
    "page_number": "77"
  },
  {
    "property_type": "Retail",
    "address": "48 170 W 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "Withheld",
    "page_number": "81"
  },
  {
    "property_type": "Retail",
    "address": "48 170 W 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1100",
    "rent_per_sf": "Withheld",
    "page_number": "81"
  },
  {
    "property_type": "Retail",
    "address": "48 170 W 23rd St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "81"
  },
  {
    "property_type": "Retail",
    "address": "50 77 W 24th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "85"
  },
  {
    "property_type": "Retail",
    "address": "50 77 W 24th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1467",
    "rent_per_sf": "Withheld",
    "page_number": "85"
  },
  {
    "property_type": "Retail",
    "address": "51 200 W 26th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1467",
    "rent_per_sf": "Withheld",
    "page_number": "87"
  },
  {
    "property_type": "Retail",
    "address": "52 118 E 28th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1190",
    "rent_per_sf": "Withheld",
    "page_number": "90"
  },
  {
    "property_type": "Retail",
    "address": "52 118 E 28th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1275",
    "rent_per_sf": "Withheld",
    "page_number": "90"
  },
  {
    "property_type": "Retail",
    "address": "53 243 W 28th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1190",
    "rent_per_sf": "Withheld",
    "page_number": "91"
  },
  {
    "property_type": "Retail",
    "address": "53 243 W 28th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1275",
    "rent_per_sf": "Withheld",
    "page_number": "91"
  },
  {
    "property_type": "Retail",
    "address": "54 14 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1275",
    "rent_per_sf": "Withheld",
    "page_number": "93"
  },
  {
    "property_type": "Retail",
    "address": "54 14 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "93"
  },
  {
    "property_type": "Retail",
    "address": "54 14 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1300",
    "rent_per_sf": "Withheld",
    "page_number": "93"
  },
  {
    "property_type": "Retail",
    "address": "54 14 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1200",
    "rent_per_sf": "Withheld",
    "page_number": "93"
  },
  {
    "property_type": "Retail",
    "address": "55 102 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "95"
  },
  {
    "property_type": "Retail",
    "address": "55 102 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1300",
    "rent_per_sf": "Withheld",
    "page_number": "95"
  },
  {
    "property_type": "Retail",
    "address": "55 102 W 29th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1200",
    "rent_per_sf": "Withheld",
    "page_number": "95"
  },
  {
    "property_type": "Retail",
    "address": "56 140 W 30th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1300",
    "rent_per_sf": "Withheld",
    "page_number": "97"
  },
  {
    "property_type": "Retail",
    "address": "56 140 W 30th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1200",
    "rent_per_sf": "Withheld",
    "page_number": "97"
  },
  {
    "property_type": "Retail",
    "address": "56 140 W 30th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1300",
    "rent_per_sf": "Withheld",
    "page_number": "97"
  },
  {
    "property_type": "Retail",
    "address": "60 45 Bleecker St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1415",
    "rent_per_sf": "Withheld",
    "page_number": "103"
  },
  {
    "property_type": "Retail",
    "address": "60 45 Bleecker St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1900",
    "rent_per_sf": "Withheld",
    "page_number": "103"
  },
  {
    "property_type": "Retail",
    "address": "60 45 Bleecker St",
    "city_state": "",
    "floor": "GRND",
    "suite": "774",
    "use_type": "Office/Retail",
    "size_sf": "725",
    "rent_per_sf": "Withheld",
    "page_number": "103"
  },
  {
    "property_type": "Retail",
    "address": "68 294 Eighth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "116"
  },
  {
    "property_type": "Retail",
    "address": "68 294 Eighth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1200",
    "rent_per_sf": "Withheld",
    "page_number": "116"
  },
  {
    "property_type": "Retail",
    "address": "68 294 Eighth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "750",
    "rent_per_sf": "Withheld",
    "page_number": "116"
  },
  {
    "property_type": "Retail",
    "address": "69 79 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1200",
    "rent_per_sf": "Withheld",
    "page_number": "118"
  },
  {
    "property_type": "Retail",
    "address": "69 79 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "750",
    "rent_per_sf": "Withheld",
    "page_number": "118"
  },
  {
    "property_type": "Retail",
    "address": "69 79 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "118"
  },
  {
    "property_type": "Retail",
    "address": "70 234 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1200",
    "rent_per_sf": "Withheld",
    "page_number": "119"
  },
  {
    "property_type": "Retail",
    "address": "70 234 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "750",
    "rent_per_sf": "Withheld",
    "page_number": "119"
  },
  {
    "property_type": "Retail",
    "address": "70 234 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "119"
  },
  {
    "property_type": "Retail",
    "address": "71 256 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "750",
    "rent_per_sf": "Withheld",
    "page_number": "120"
  },
  {
    "property_type": "Retail",
    "address": "71 256 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "120"
  },
  {
    "property_type": "Retail",
    "address": "71 256 Fifth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "620",
    "rent_per_sf": "Withheld",
    "page_number": "120"
  },
  {
    "property_type": "Retail",
    "address": "72 3 Great Jones St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "122"
  },
  {
    "property_type": "Retail",
    "address": "72 3 Great Jones St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "620",
    "rent_per_sf": "Withheld",
    "page_number": "122"
  },
  {
    "property_type": "Retail",
    "address": "72 3 Great Jones St",
    "city_state": "",
    "floor": "GRND",
    "suite": "109",
    "use_type": "Retail",
    "size_sf": "1866",
    "rent_per_sf": "Withheld",
    "page_number": "122"
  },
  {
    "property_type": "Retail",
    "address": "72 3 Great Jones St",
    "city_state": "",
    "floor": "GRND",
    "suite": "104",
    "use_type": "Retail",
    "size_sf": "1182",
    "rent_per_sf": "Withheld",
    "page_number": "122"
  },
  {
    "property_type": "Retail",
    "address": "73 25 Great Jones St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "620",
    "rent_per_sf": "Withheld",
    "page_number": "124"
  },
  {
    "property_type": "Retail",
    "address": "73 25 Great Jones St",
    "city_state": "",
    "floor": "GRND",
    "suite": "109",
    "use_type": "Retail",
    "size_sf": "1866",
    "rent_per_sf": "Withheld",
    "page_number": "124"
  },
  {
    "property_type": "Retail",
    "address": "73 25 Great Jones St",
    "city_state": "",
    "floor": "GRND",
    "suite": "104",
    "use_type": "Retail",
    "size_sf": "1182",
    "rent_per_sf": "Withheld",
    "page_number": "124"
  },
  {
    "property_type": "Retail",
    "address": "73 25 Great Jones St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1250",
    "rent_per_sf": "Withheld",
    "page_number": "124"
  },
  {
    "property_type": "Retail",
    "address": "74 1 Irving Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "109",
    "use_type": "Retail",
    "size_sf": "1866",
    "rent_per_sf": "Withheld",
    "page_number": "126"
  },
  {
    "property_type": "Retail",
    "address": "74 1 Irving Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "104",
    "use_type": "Retail",
    "size_sf": "1182",
    "rent_per_sf": "Withheld",
    "page_number": "126"
  },
  {
    "property_type": "Retail",
    "address": "74 1 Irving Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1250",
    "rent_per_sf": "Withheld",
    "page_number": "126"
  },
  {
    "property_type": "Retail",
    "address": "74 1 Irving Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "Ground",
    "use_type": "Retail",
    "size_sf": "1019",
    "rent_per_sf": "Withheld",
    "page_number": "126"
  },
  {
    "property_type": "Retail",
    "address": "75 372 Lafayette St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1250",
    "rent_per_sf": "Withheld",
    "page_number": "128"
  },
  {
    "property_type": "Retail",
    "address": "75 372 Lafayette St",
    "city_state": "",
    "floor": "GRND",
    "suite": "Ground",
    "use_type": "Retail",
    "size_sf": "1019",
    "rent_per_sf": "Withheld",
    "page_number": "128"
  },
  {
    "property_type": "Retail",
    "address": "75 372 Lafayette St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1000",
    "rent_per_sf": "Withheld",
    "page_number": "128"
  },
  {
    "property_type": "Retail",
    "address": "76 445 Lafayette St",
    "city_state": "",
    "floor": "GRND",
    "suite": "Ground",
    "use_type": "Retail",
    "size_sf": "1019",
    "rent_per_sf": "Withheld",
    "page_number": "130"
  },
  {
    "property_type": "Retail",
    "address": "76 445 Lafayette St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1000",
    "rent_per_sf": "Withheld",
    "page_number": "130"
  },
  {
    "property_type": "Retail",
    "address": "76 445 Lafayette St",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1300",
    "rent_per_sf": "Withheld",
    "page_number": "130"
  },
  {
    "property_type": "Retail",
    "address": "76 445 Lafayette St",
    "city_state": "",
    "floor": "GRND",
    "suite": "B",
    "use_type": "Retail",
    "size_sf": "1100",
    "rent_per_sf": "Withheld",
    "page_number": "130"
  },
  {
    "property_type": "Retail",
    "address": "78 121 Madison Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1300",
    "rent_per_sf": "Withheld",
    "page_number": "134"
  },
  {
    "property_type": "Retail",
    "address": "78 121 Madison Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "B",
    "use_type": "Retail",
    "size_sf": "1100",
    "rent_per_sf": "Withheld",
    "page_number": "134"
  },
  {
    "property_type": "Retail",
    "address": "78 121 Madison Ave",
    "city_state": "",
    "floor": "",
    "suite": "687",
    "use_type": "Retail",
    "size_sf": "1050",
    "rent_per_sf": "Withheld",
    "page_number": "134"
  },
  {
    "property_type": "Retail",
    "address": "78 121 Madison Ave",
    "city_state": "",
    "floor": "",
    "suite": "683",
    "use_type": "Retail",
    "size_sf": "1000",
    "rent_per_sf": "Withheld",
    "page_number": "134"
  },
  {
    "property_type": "Retail",
    "address": "78 121 Madison Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1100",
    "rent_per_sf": "Withheld",
    "page_number": "134"
  },
  {
    "property_type": "Retail",
    "address": "79 250 Mercer St",
    "city_state": "",
    "floor": "",
    "suite": "687",
    "use_type": "Retail",
    "size_sf": "1050",
    "rent_per_sf": "Withheld",
    "page_number": "136"
  },
  {
    "property_type": "Retail",
    "address": "79 250 Mercer St",
    "city_state": "",
    "floor": "",
    "suite": "683",
    "use_type": "Retail",
    "size_sf": "1000",
    "rent_per_sf": "Withheld",
    "page_number": "136"
  },
  {
    "property_type": "Retail",
    "address": "79 250 Mercer St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1100",
    "rent_per_sf": "Withheld",
    "page_number": "136"
  },
  {
    "property_type": "Retail",
    "address": "79 250 Mercer St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1027",
    "rent_per_sf": "Withheld",
    "page_number": "136"
  },
  {
    "property_type": "Retail",
    "address": "79 250 Mercer St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "136"
  },
  {
    "property_type": "Retail",
    "address": "80 337 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1100",
    "rent_per_sf": "Withheld",
    "page_number": "138"
  },
  {
    "property_type": "Retail",
    "address": "80 337 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1027",
    "rent_per_sf": "Withheld",
    "page_number": "138"
  },
  {
    "property_type": "Retail",
    "address": "80 337 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "138"
  },
  {
    "property_type": "Retail",
    "address": "80 337 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1987",
    "rent_per_sf": "Withheld",
    "page_number": "138"
  },
  {
    "property_type": "Retail",
    "address": "81 470 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1027",
    "rent_per_sf": "Withheld",
    "page_number": "139"
  },
  {
    "property_type": "Retail",
    "address": "81 470 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "139"
  },
  {
    "property_type": "Retail",
    "address": "81 470 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1987",
    "rent_per_sf": "Withheld",
    "page_number": "139"
  },
  {
    "property_type": "Retail",
    "address": "83 275 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1987",
    "rent_per_sf": "Withheld",
    "page_number": "142"
  },
  {
    "property_type": "Retail",
    "address": "83 275 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "142"
  },
  {
    "property_type": "Retail",
    "address": "83 275 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "Withheld",
    "page_number": "142"
  },
  {
    "property_type": "Retail",
    "address": "83 275 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "142"
  },
  {
    "property_type": "Retail",
    "address": "84 287 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "2000",
    "rent_per_sf": "Withheld",
    "page_number": "143"
  },
  {
    "property_type": "Retail",
    "address": "84 287 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "Withheld",
    "page_number": "143"
  },
  {
    "property_type": "Retail",
    "address": "84 287 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "143"
  },
  {
    "property_type": "Retail",
    "address": "85 299 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1700",
    "rent_per_sf": "Withheld",
    "page_number": "145"
  },
  {
    "property_type": "Retail",
    "address": "85 299 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "145"
  },
  {
    "property_type": "Retail",
    "address": "85 299 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "145"
  },
  {
    "property_type": "Retail",
    "address": "86 345 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "A",
    "use_type": "Retail",
    "size_sf": "1500",
    "rent_per_sf": "Withheld",
    "page_number": "147"
  },
  {
    "property_type": "Retail",
    "address": "86 345 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "147"
  },
  {
    "property_type": "Retail",
    "address": "86 345 Seventh Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "812",
    "rent_per_sf": "Withheld",
    "page_number": "147"
  },
  {
    "property_type": "Retail",
    "address": "88 388 Third Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1600",
    "rent_per_sf": "Withheld",
    "page_number": "149"
  },
  {
    "property_type": "Retail",
    "address": "88 388 Third Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "812",
    "rent_per_sf": "Withheld",
    "page_number": "149"
  },
  {
    "property_type": "Retail",
    "address": "88 388 Third Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1390",
    "rent_per_sf": "Withheld",
    "page_number": "149"
  },
  {
    "property_type": "Retail",
    "address": "89 441 Third Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "812",
    "rent_per_sf": "Withheld",
    "page_number": "151"
  },
  {
    "property_type": "Retail",
    "address": "89 441 Third Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1390",
    "rent_per_sf": "Withheld",
    "page_number": "151"
  },
  {
    "property_type": "Retail",
    "address": "89 441 Third Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1000",
    "rent_per_sf": "Withheld",
    "page_number": "151"
  },
  {
    "property_type": "Retail",
    "address": "91 11 Waverly Pl",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Retail",
    "size_sf": "1000",
    "rent_per_sf": "Withheld",
    "page_number": "155"
  },
  {
    "property_type": "Office",
    "address": "1 27 W 20th St",
    "city_state": "",
    "floor": "12",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "500",
    "rent_per_sf": "$3.00",
    "page_number": "1"
  },
  {
    "property_type": "Office",
    "address": "1 27 W 20th St",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office/Medical",
    "size_sf": "3005",
    "rent_per_sf": "$3.33",
    "page_number": "1"
  },
  {
    "property_type": "Office",
    "address": "2 134 W 29th St",
    "city_state": "",
    "floor": "12",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "500",
    "rent_per_sf": "$3.00",
    "page_number": "2"
  },
  {
    "property_type": "Office",
    "address": "2 134 W 29th St",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office/Medical",
    "size_sf": "3005",
    "rent_per_sf": "$3.33",
    "page_number": "2"
  },
  {
    "property_type": "Office",
    "address": "3 115 E 23rd St",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office/Medical",
    "size_sf": "3005",
    "rent_per_sf": "$3.33",
    "page_number": "3"
  },
  {
    "property_type": "Office",
    "address": "5 242 W 30th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4911",
    "rent_per_sf": "$3.00",
    "page_number": "6"
  },
  {
    "property_type": "Office",
    "address": "6 119 W 23rd St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4911",
    "rent_per_sf": "$3.00",
    "page_number": "8"
  },
  {
    "property_type": "Office",
    "address": "6 119 W 23rd St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "8"
  },
  {
    "property_type": "Office",
    "address": "6 119 W 23rd St",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$3.04",
    "page_number": "8"
  },
  {
    "property_type": "Office",
    "address": "7 134 W 25th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4911",
    "rent_per_sf": "$3.00",
    "page_number": "9"
  },
  {
    "property_type": "Office",
    "address": "7 134 W 25th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "9"
  },
  {
    "property_type": "Office",
    "address": "7 134 W 25th St",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$3.04",
    "page_number": "9"
  },
  {
    "property_type": "Office",
    "address": "7 134 W 25th St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2500",
    "rent_per_sf": "$4.79",
    "page_number": "9"
  },
  {
    "property_type": "Office",
    "address": "7 134 W 25th St",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2500",
    "rent_per_sf": "$4.79",
    "page_number": "9"
  },
  {
    "property_type": "Office",
    "address": "8 134 W 26th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "11"
  },
  {
    "property_type": "Office",
    "address": "8 134 W 26th St",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$3.04",
    "page_number": "11"
  },
  {
    "property_type": "Office",
    "address": "8 134 W 26th St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2500",
    "rent_per_sf": "$4.79",
    "page_number": "11"
  },
  {
    "property_type": "Office",
    "address": "8 134 W 26th St",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2500",
    "rent_per_sf": "$4.79",
    "page_number": "11"
  },
  {
    "property_type": "Office",
    "address": "8 134 W 26th St",
    "city_state": "",
    "floor": "19",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "1000",
    "rent_per_sf": "",
    "page_number": "11"
  },
  {
    "property_type": "Office",
    "address": "9 141 W 28th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "12"
  },
  {
    "property_type": "Office",
    "address": "9 141 W 28th St",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$3.04",
    "page_number": "12"
  },
  {
    "property_type": "Office",
    "address": "9 141 W 28th St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2500",
    "rent_per_sf": "$4.79",
    "page_number": "12"
  },
  {
    "property_type": "Office",
    "address": "9 141 W 28th St",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2500",
    "rent_per_sf": "$4.79",
    "page_number": "12"
  },
  {
    "property_type": "Office",
    "address": "9 141 W 28th St",
    "city_state": "",
    "floor": "19",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "1000",
    "rent_per_sf": "",
    "page_number": "12"
  },
  {
    "property_type": "Office",
    "address": "9 141 W 28th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3300",
    "rent_per_sf": "",
    "page_number": "12"
  },
  {
    "property_type": "Office",
    "address": "11 307 Seventh Ave",
    "city_state": "",
    "floor": "19",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "1000",
    "rent_per_sf": "",
    "page_number": "14"
  },
  {
    "property_type": "Office",
    "address": "11 307 Seventh Ave",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3300",
    "rent_per_sf": "",
    "page_number": "14"
  },
  {
    "property_type": "Office",
    "address": "11 307 Seventh Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "",
    "page_number": "14"
  },
  {
    "property_type": "Office",
    "address": "12 220 E 23rd St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3300",
    "rent_per_sf": "",
    "page_number": "15"
  },
  {
    "property_type": "Office",
    "address": "12 220 E 23rd St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "",
    "page_number": "15"
  },
  {
    "property_type": "Office",
    "address": "12 220 E 23rd St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "$3.75",
    "page_number": "15"
  },
  {
    "property_type": "Office",
    "address": "14 281 Park Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "$3.75",
    "page_number": "18"
  },
  {
    "property_type": "Office",
    "address": "14 281 Park Ave",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2325",
    "rent_per_sf": "$4.58",
    "page_number": "18"
  },
  {
    "property_type": "Office",
    "address": "14 281 Park Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2325",
    "rent_per_sf": "",
    "page_number": "18"
  },
  {
    "property_type": "Office",
    "address": "14 281 Park Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2500",
    "rent_per_sf": "$2.92",
    "page_number": "18"
  },
  {
    "property_type": "Office",
    "address": "15 134 5th Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "$3.75",
    "page_number": "19"
  },
  {
    "property_type": "Office",
    "address": "15 134 5th Ave",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2325",
    "rent_per_sf": "$4.58",
    "page_number": "19"
  },
  {
    "property_type": "Office",
    "address": "15 134 5th Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2325",
    "rent_per_sf": "",
    "page_number": "19"
  },
  {
    "property_type": "Office",
    "address": "15 134 5th Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2500",
    "rent_per_sf": "$2.92",
    "page_number": "19"
  },
  {
    "property_type": "Office",
    "address": "15 134 5th Ave",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "$3.83",
    "page_number": "19"
  },
  {
    "property_type": "Office",
    "address": "16 21 E 17th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2325",
    "rent_per_sf": "$4.58",
    "page_number": "20"
  },
  {
    "property_type": "Office",
    "address": "16 21 E 17th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2325",
    "rent_per_sf": "",
    "page_number": "20"
  },
  {
    "property_type": "Office",
    "address": "16 21 E 17th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2500",
    "rent_per_sf": "$2.92",
    "page_number": "20"
  },
  {
    "property_type": "Office",
    "address": "16 21 E 17th St",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "$3.83",
    "page_number": "20"
  },
  {
    "property_type": "Office",
    "address": "16 21 E 17th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$4.42",
    "page_number": "20"
  },
  {
    "property_type": "Office",
    "address": "18 133 W 19th St",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "$3.83",
    "page_number": "23"
  },
  {
    "property_type": "Office",
    "address": "18 133 W 19th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$4.42",
    "page_number": "23"
  },
  {
    "property_type": "Office",
    "address": "18 133 W 19th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4300",
    "rent_per_sf": "$4.33",
    "page_number": "23"
  },
  {
    "property_type": "Office",
    "address": "19 45 E 20th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$4.42",
    "page_number": "24"
  },
  {
    "property_type": "Office",
    "address": "19 45 E 20th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4300",
    "rent_per_sf": "$4.33",
    "page_number": "24"
  },
  {
    "property_type": "Office",
    "address": "19 45 E 20th St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "",
    "page_number": "24"
  },
  {
    "property_type": "Office",
    "address": "21 117 E 24th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4300",
    "rent_per_sf": "$4.33",
    "page_number": "26"
  },
  {
    "property_type": "Office",
    "address": "21 117 E 24th St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "",
    "page_number": "26"
  },
  {
    "property_type": "Office",
    "address": "21 117 E 24th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "200",
    "rent_per_sf": "",
    "page_number": "26"
  },
  {
    "property_type": "Office",
    "address": "21 117 E 24th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "100",
    "rent_per_sf": "",
    "page_number": "26"
  },
  {
    "property_type": "Office",
    "address": "21 117 E 24th St",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "$4.92",
    "page_number": "26"
  },
  {
    "property_type": "Office",
    "address": "23 148 W 24th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "200",
    "rent_per_sf": "",
    "page_number": "29"
  },
  {
    "property_type": "Office",
    "address": "23 148 W 24th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "100",
    "rent_per_sf": "",
    "page_number": "29"
  },
  {
    "property_type": "Office",
    "address": "23 148 W 24th St",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "$4.92",
    "page_number": "29"
  },
  {
    "property_type": "Office",
    "address": "23 148 W 24th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "$3.00",
    "page_number": "29"
  },
  {
    "property_type": "Office",
    "address": "24 159 W 25th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "200",
    "rent_per_sf": "",
    "page_number": "30"
  },
  {
    "property_type": "Office",
    "address": "24 159 W 25th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "100",
    "rent_per_sf": "",
    "page_number": "30"
  },
  {
    "property_type": "Office",
    "address": "24 159 W 25th St",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "$4.92",
    "page_number": "30"
  },
  {
    "property_type": "Office",
    "address": "24 159 W 25th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "$3.00",
    "page_number": "30"
  },
  {
    "property_type": "Office",
    "address": "25 164 W 25th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "$3.00",
    "page_number": "31"
  },
  {
    "property_type": "Office",
    "address": "27 151 W 26th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4184",
    "rent_per_sf": "$3.17",
    "page_number": "34"
  },
  {
    "property_type": "Office",
    "address": "27 151 W 26th St",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$2.50",
    "page_number": "34"
  },
  {
    "property_type": "Office",
    "address": "28 226 W 26th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4184",
    "rent_per_sf": "$3.17",
    "page_number": "35"
  },
  {
    "property_type": "Office",
    "address": "28 226 W 26th St",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$2.50",
    "page_number": "35"
  },
  {
    "property_type": "Office",
    "address": "30 28 W 27th St",
    "city_state": "",
    "floor": "10",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$2.50",
    "page_number": "38"
  },
  {
    "property_type": "Office",
    "address": "30 28 W 27th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4000",
    "rent_per_sf": "$3.25",
    "page_number": "38"
  },
  {
    "property_type": "Office",
    "address": "34 39 W 29th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$2.67",
    "page_number": "44"
  },
  {
    "property_type": "Office",
    "address": "34 39 W 29th St",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3500",
    "rent_per_sf": "$3.00",
    "page_number": "44"
  },
  {
    "property_type": "Office",
    "address": "34 39 W 29th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "$3.33",
    "page_number": "44"
  },
  {
    "property_type": "Office",
    "address": "37 110 W 30th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4500",
    "rent_per_sf": "$3.33",
    "page_number": "47"
  },
  {
    "property_type": "Office",
    "address": "37 110 W 30th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2400",
    "rent_per_sf": "$4.04",
    "page_number": "47"
  },
  {
    "property_type": "Office",
    "address": "37 110 W 30th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2300",
    "rent_per_sf": "$4.04",
    "page_number": "47"
  },
  {
    "property_type": "Office",
    "address": "37 110 W 30th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2000",
    "rent_per_sf": "",
    "page_number": "47"
  },
  {
    "property_type": "Office",
    "address": "37 110 W 30th St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4000",
    "rent_per_sf": "$3.50",
    "page_number": "47"
  },
  {
    "property_type": "Office",
    "address": "38 234 W 30th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2400",
    "rent_per_sf": "$4.04",
    "page_number": "48"
  },
  {
    "property_type": "Office",
    "address": "38 234 W 30th St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2300",
    "rent_per_sf": "$4.04",
    "page_number": "48"
  },
  {
    "property_type": "Office",
    "address": "38 234 W 30th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2000",
    "rent_per_sf": "",
    "page_number": "48"
  },
  {
    "property_type": "Office",
    "address": "38 234 W 30th St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4000",
    "rent_per_sf": "$3.50",
    "page_number": "48"
  },
  {
    "property_type": "Office",
    "address": "43 119 Fifth Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4134",
    "rent_per_sf": "",
    "page_number": "54"
  },
  {
    "property_type": "Office",
    "address": "43 119 Fifth Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$4.17",
    "page_number": "54"
  },
  {
    "property_type": "Office",
    "address": "43 119 Fifth Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4465",
    "rent_per_sf": "",
    "page_number": "54"
  },
  {
    "property_type": "Office",
    "address": "43 119 Fifth Ave",
    "city_state": "",
    "floor": "17",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2121",
    "rent_per_sf": "$5.42",
    "page_number": "54"
  },
  {
    "property_type": "Office",
    "address": "43 119 Fifth Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "54"
  },
  {
    "property_type": "Office",
    "address": "43 119 Fifth Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "54"
  },
  {
    "property_type": "Office",
    "address": "43 119 Fifth Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "54"
  },
  {
    "property_type": "Office",
    "address": "43 119 Fifth Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "54"
  },
  {
    "property_type": "Office",
    "address": "44 255 Fifth Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "$4.17",
    "page_number": "55"
  },
  {
    "property_type": "Office",
    "address": "44 255 Fifth Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4465",
    "rent_per_sf": "",
    "page_number": "55"
  },
  {
    "property_type": "Office",
    "address": "44 255 Fifth Ave",
    "city_state": "",
    "floor": "17",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2121",
    "rent_per_sf": "$5.42",
    "page_number": "55"
  },
  {
    "property_type": "Office",
    "address": "44 255 Fifth Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "55"
  },
  {
    "property_type": "Office",
    "address": "44 255 Fifth Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "55"
  },
  {
    "property_type": "Office",
    "address": "44 255 Fifth Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "55"
  },
  {
    "property_type": "Office",
    "address": "44 255 Fifth Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "55"
  },
  {
    "property_type": "Office",
    "address": "45 116 W Houston St",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4465",
    "rent_per_sf": "",
    "page_number": "56"
  },
  {
    "property_type": "Office",
    "address": "45 116 W Houston St",
    "city_state": "",
    "floor": "17",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2121",
    "rent_per_sf": "$5.42",
    "page_number": "56"
  },
  {
    "property_type": "Office",
    "address": "45 116 W Houston St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "56"
  },
  {
    "property_type": "Office",
    "address": "45 116 W Houston St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "56"
  },
  {
    "property_type": "Office",
    "address": "45 116 W Houston St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "56"
  },
  {
    "property_type": "Office",
    "address": "45 116 W Houston St",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "56"
  },
  {
    "property_type": "Office",
    "address": "45 116 W Houston St",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Medical",
    "size_sf": "4000",
    "rent_per_sf": "Withheld",
    "page_number": "56"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "17",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2121",
    "rent_per_sf": "$5.42",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Medical",
    "size_sf": "4000",
    "rent_per_sf": "Withheld",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "46 352 Park Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "57"
  },
  {
    "property_type": "Office",
    "address": "47 838 Sixth Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "58"
  },
  {
    "property_type": "Office",
    "address": "47 838 Sixth Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "58"
  },
  {
    "property_type": "Office",
    "address": "47 838 Sixth Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "58"
  },
  {
    "property_type": "Office",
    "address": "47 838 Sixth Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4750",
    "rent_per_sf": "$2.50",
    "page_number": "58"
  },
  {
    "property_type": "Office",
    "address": "47 838 Sixth Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Medical",
    "size_sf": "4000",
    "rent_per_sf": "Withheld",
    "page_number": "58"
  },
  {
    "property_type": "Office",
    "address": "47 838 Sixth Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "58"
  },
  {
    "property_type": "Office",
    "address": "47 838 Sixth Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "58"
  },
  {
    "property_type": "Office",
    "address": "47 838 Sixth Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "58"
  },
  {
    "property_type": "Office",
    "address": "48 233 3rd Ave",
    "city_state": "",
    "floor": "GRND",
    "suite": "-",
    "use_type": "Office/Medical",
    "size_sf": "4000",
    "rent_per_sf": "Withheld",
    "page_number": "59"
  },
  {
    "property_type": "Office",
    "address": "48 233 3rd Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "59"
  },
  {
    "property_type": "Office",
    "address": "48 233 3rd Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "59"
  },
  {
    "property_type": "Office",
    "address": "48 233 3rd Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4890",
    "rent_per_sf": "",
    "page_number": "59"
  },
  {
    "property_type": "Office",
    "address": "50 25 W 14th St",
    "city_state": "",
    "floor": "11",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3921",
    "rent_per_sf": "",
    "page_number": "63"
  },
  {
    "property_type": "Office",
    "address": "50 25 W 14th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4100",
    "rent_per_sf": "",
    "page_number": "63"
  },
  {
    "property_type": "Office",
    "address": "51 22 W 19th St",
    "city_state": "",
    "floor": "11",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3921",
    "rent_per_sf": "",
    "page_number": "64"
  },
  {
    "property_type": "Office",
    "address": "51 22 W 19th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4100",
    "rent_per_sf": "",
    "page_number": "64"
  },
  {
    "property_type": "Office",
    "address": "51 22 W 19th St",
    "city_state": "",
    "floor": "12",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "64"
  },
  {
    "property_type": "Office",
    "address": "51 22 W 19th St",
    "city_state": "",
    "floor": "15",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "64"
  },
  {
    "property_type": "Office",
    "address": "52 220 W 19th St",
    "city_state": "",
    "floor": "11",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3921",
    "rent_per_sf": "",
    "page_number": "65"
  },
  {
    "property_type": "Office",
    "address": "52 220 W 19th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4100",
    "rent_per_sf": "",
    "page_number": "65"
  },
  {
    "property_type": "Office",
    "address": "52 220 W 19th St",
    "city_state": "",
    "floor": "12",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "65"
  },
  {
    "property_type": "Office",
    "address": "52 220 W 19th St",
    "city_state": "",
    "floor": "15",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "65"
  },
  {
    "property_type": "Office",
    "address": "54 36 W 25th St",
    "city_state": "",
    "floor": "12",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "67"
  },
  {
    "property_type": "Office",
    "address": "54 36 W 25th St",
    "city_state": "",
    "floor": "15",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "67"
  },
  {
    "property_type": "Office",
    "address": "54 36 W 25th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "67"
  },
  {
    "property_type": "Office",
    "address": "54 36 W 25th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "67"
  },
  {
    "property_type": "Office",
    "address": "55 125 W 25th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "68"
  },
  {
    "property_type": "Office",
    "address": "55 125 W 25th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "68"
  },
  {
    "property_type": "Office",
    "address": "55 125 W 25th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "68"
  },
  {
    "property_type": "Office",
    "address": "55 125 W 25th St",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "68"
  },
  {
    "property_type": "Office",
    "address": "55 125 W 25th St",
    "city_state": "",
    "floor": "12",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "68"
  },
  {
    "property_type": "Office",
    "address": "56 25 W 26th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "69"
  },
  {
    "property_type": "Office",
    "address": "56 25 W 26th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "69"
  },
  {
    "property_type": "Office",
    "address": "56 25 W 26th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "69"
  },
  {
    "property_type": "Office",
    "address": "56 25 W 26th St",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "69"
  },
  {
    "property_type": "Office",
    "address": "56 25 W 26th St",
    "city_state": "",
    "floor": "12",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "69"
  },
  {
    "property_type": "Office",
    "address": "56 25 W 26th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4400",
    "rent_per_sf": "Withheld",
    "page_number": "69"
  },
  {
    "property_type": "Office",
    "address": "57 109 W 27th St",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "71"
  },
  {
    "property_type": "Office",
    "address": "57 109 W 27th St",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "71"
  },
  {
    "property_type": "Office",
    "address": "57 109 W 27th St",
    "city_state": "",
    "floor": "12",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "71"
  },
  {
    "property_type": "Office",
    "address": "57 109 W 27th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4400",
    "rent_per_sf": "Withheld",
    "page_number": "71"
  },
  {
    "property_type": "Office",
    "address": "57 109 W 27th St",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "71"
  },
  {
    "property_type": "Office",
    "address": "59 37 E 28th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4400",
    "rent_per_sf": "Withheld",
    "page_number": "73"
  },
  {
    "property_type": "Office",
    "address": "59 37 E 28th St",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "73"
  },
  {
    "property_type": "Office",
    "address": "60 37 W 28th St",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "5000",
    "rent_per_sf": "",
    "page_number": "74"
  },
  {
    "property_type": "Office",
    "address": "60 37 W 28th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4832",
    "rent_per_sf": "",
    "page_number": "74"
  },
  {
    "property_type": "Office",
    "address": "61 205 W 28th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4832",
    "rent_per_sf": "",
    "page_number": "75"
  },
  {
    "property_type": "Office",
    "address": "61 205 W 28th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4330",
    "rent_per_sf": "Withheld",
    "page_number": "75"
  },
  {
    "property_type": "Office",
    "address": "62 104 W 29th St",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4832",
    "rent_per_sf": "",
    "page_number": "76"
  },
  {
    "property_type": "Office",
    "address": "62 104 W 29th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4330",
    "rent_per_sf": "Withheld",
    "page_number": "76"
  },
  {
    "property_type": "Office",
    "address": "64 22 E 30th St",
    "city_state": "",
    "floor": "",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "4330",
    "rent_per_sf": "Withheld",
    "page_number": "78"
  },
  {
    "property_type": "Office",
    "address": "64 22 E 30th St",
    "city_state": "",
    "floor": "1",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2897",
    "rent_per_sf": "",
    "page_number": "78"
  },
  {
    "property_type": "Office",
    "address": "64 22 E 30th St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2900",
    "rent_per_sf": "",
    "page_number": "78"
  },
  {
    "property_type": "Office",
    "address": "64 22 E 30th St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2966",
    "rent_per_sf": "",
    "page_number": "78"
  },
  {
    "property_type": "Office",
    "address": "64 22 E 30th St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2984",
    "rent_per_sf": "",
    "page_number": "78"
  },
  {
    "property_type": "Office",
    "address": "64 22 E 30th St",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2988",
    "rent_per_sf": "",
    "page_number": "78"
  },
  {
    "property_type": "Office",
    "address": "64 22 E 30th St",
    "city_state": "",
    "floor": "11",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4578",
    "rent_per_sf": "",
    "page_number": "78"
  },
  {
    "property_type": "Office",
    "address": "66 31 Bond St",
    "city_state": "",
    "floor": "1",
    "suite": "-",
    "use_type": "Office/Retail",
    "size_sf": "2897",
    "rent_per_sf": "",
    "page_number": "80"
  },
  {
    "property_type": "Office",
    "address": "66 31 Bond St",
    "city_state": "",
    "floor": "2",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2900",
    "rent_per_sf": "",
    "page_number": "80"
  },
  {
    "property_type": "Office",
    "address": "66 31 Bond St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2966",
    "rent_per_sf": "",
    "page_number": "80"
  },
  {
    "property_type": "Office",
    "address": "66 31 Bond St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2984",
    "rent_per_sf": "",
    "page_number": "80"
  },
  {
    "property_type": "Office",
    "address": "66 31 Bond St",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2988",
    "rent_per_sf": "",
    "page_number": "80"
  },
  {
    "property_type": "Office",
    "address": "66 31 Bond St",
    "city_state": "",
    "floor": "11",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4578",
    "rent_per_sf": "",
    "page_number": "80"
  },
  {
    "property_type": "Office",
    "address": "66 31 Bond St",
    "city_state": "",
    "floor": "GRND",
    "suite": "774",
    "use_type": "Office/Retail",
    "size_sf": "725",
    "rent_per_sf": "Withheld",
    "page_number": "80"
  },
  {
    "property_type": "Office",
    "address": "73 166 Crosby St",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "1000",
    "rent_per_sf": "",
    "page_number": "89"
  },
  {
    "property_type": "Office",
    "address": "73 166 Crosby St",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "100",
    "rent_per_sf": "",
    "page_number": "89"
  },
  {
    "property_type": "Office",
    "address": "74 245 Fifth Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "100",
    "rent_per_sf": "",
    "page_number": "90"
  },
  {
    "property_type": "Office",
    "address": "75 246 Fifth Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "100",
    "rent_per_sf": "",
    "page_number": "91"
  },
  {
    "property_type": "Office",
    "address": "76 261 Fifth Ave",
    "city_state": "",
    "floor": "",
    "suite": "8",
    "use_type": "815/817/819Office",
    "size_sf": "4388",
    "rent_per_sf": "Withheld",
    "page_number": "92"
  },
  {
    "property_type": "Office",
    "address": "77 333 Park Ave",
    "city_state": "",
    "floor": "",
    "suite": "8",
    "use_type": "815/817/819Office",
    "size_sf": "4388",
    "rent_per_sf": "Withheld",
    "page_number": "93"
  },
  {
    "property_type": "Office",
    "address": "77 333 Park Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4765",
    "rent_per_sf": "",
    "page_number": "93"
  },
  {
    "property_type": "Office",
    "address": "77 333 Park Ave",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4748",
    "rent_per_sf": "",
    "page_number": "93"
  },
  {
    "property_type": "Office",
    "address": "77 333 Park Ave",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4765",
    "rent_per_sf": "",
    "page_number": "93"
  },
  {
    "property_type": "Office",
    "address": "77 333 Park Ave",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2062",
    "rent_per_sf": "",
    "page_number": "93"
  },
  {
    "property_type": "Office",
    "address": "78 377 Park Ave",
    "city_state": "",
    "floor": "",
    "suite": "8",
    "use_type": "815/817/819Office",
    "size_sf": "4388",
    "rent_per_sf": "Withheld",
    "page_number": "94"
  },
  {
    "property_type": "Office",
    "address": "78 377 Park Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4765",
    "rent_per_sf": "",
    "page_number": "94"
  },
  {
    "property_type": "Office",
    "address": "78 377 Park Ave",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4748",
    "rent_per_sf": "",
    "page_number": "94"
  },
  {
    "property_type": "Office",
    "address": "78 377 Park Ave",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4765",
    "rent_per_sf": "",
    "page_number": "94"
  },
  {
    "property_type": "Office",
    "address": "78 377 Park Ave",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2062",
    "rent_per_sf": "",
    "page_number": "94"
  },
  {
    "property_type": "Office",
    "address": "79 381 Park Ave",
    "city_state": "",
    "floor": "",
    "suite": "8",
    "use_type": "815/817/819Office",
    "size_sf": "4388",
    "rent_per_sf": "Withheld",
    "page_number": "96"
  },
  {
    "property_type": "Office",
    "address": "79 381 Park Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4765",
    "rent_per_sf": "",
    "page_number": "96"
  },
  {
    "property_type": "Office",
    "address": "79 381 Park Ave",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4748",
    "rent_per_sf": "",
    "page_number": "96"
  },
  {
    "property_type": "Office",
    "address": "79 381 Park Ave",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4765",
    "rent_per_sf": "",
    "page_number": "96"
  },
  {
    "property_type": "Office",
    "address": "79 381 Park Ave",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2062",
    "rent_per_sf": "",
    "page_number": "96"
  },
  {
    "property_type": "Office",
    "address": "79 381 Park Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4444",
    "rent_per_sf": "",
    "page_number": "96"
  },
  {
    "property_type": "Office",
    "address": "80 1 Saint Marks Pl",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4765",
    "rent_per_sf": "",
    "page_number": "97"
  },
  {
    "property_type": "Office",
    "address": "80 1 Saint Marks Pl",
    "city_state": "",
    "floor": "7",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4748",
    "rent_per_sf": "",
    "page_number": "97"
  },
  {
    "property_type": "Office",
    "address": "80 1 Saint Marks Pl",
    "city_state": "",
    "floor": "8",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4765",
    "rent_per_sf": "",
    "page_number": "97"
  },
  {
    "property_type": "Office",
    "address": "80 1 Saint Marks Pl",
    "city_state": "",
    "floor": "9",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "2062",
    "rent_per_sf": "",
    "page_number": "97"
  },
  {
    "property_type": "Office",
    "address": "80 1 Saint Marks Pl",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4444",
    "rent_per_sf": "",
    "page_number": "97"
  },
  {
    "property_type": "Office",
    "address": "80 1 Saint Marks Pl",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3900",
    "rent_per_sf": "",
    "page_number": "97"
  },
  {
    "property_type": "Office",
    "address": "80 1 Saint Marks Pl",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3900",
    "rent_per_sf": "",
    "page_number": "97"
  },
  {
    "property_type": "Office",
    "address": "81 330 Seventh Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4444",
    "rent_per_sf": "",
    "page_number": "98"
  },
  {
    "property_type": "Office",
    "address": "81 330 Seventh Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3900",
    "rent_per_sf": "",
    "page_number": "98"
  },
  {
    "property_type": "Office",
    "address": "81 330 Seventh Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3900",
    "rent_per_sf": "",
    "page_number": "98"
  },
  {
    "property_type": "Office",
    "address": "81 330 Seventh Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "98"
  },
  {
    "property_type": "Office",
    "address": "81 330 Seventh Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "98"
  },
  {
    "property_type": "Office",
    "address": "81 330 Seventh Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "98"
  },
  {
    "property_type": "Office",
    "address": "82 350 Seventh Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4444",
    "rent_per_sf": "",
    "page_number": "99"
  },
  {
    "property_type": "Office",
    "address": "82 350 Seventh Ave",
    "city_state": "",
    "floor": "3",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3900",
    "rent_per_sf": "",
    "page_number": "99"
  },
  {
    "property_type": "Office",
    "address": "82 350 Seventh Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "3900",
    "rent_per_sf": "",
    "page_number": "99"
  },
  {
    "property_type": "Office",
    "address": "82 350 Seventh Ave",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "99"
  },
  {
    "property_type": "Office",
    "address": "82 350 Seventh Ave",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "99"
  },
  {
    "property_type": "Office",
    "address": "82 350 Seventh Ave",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "99"
  },
  {
    "property_type": "Office",
    "address": "85 99 University Pl",
    "city_state": "",
    "floor": "4",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "102"
  },
  {
    "property_type": "Office",
    "address": "85 99 University Pl",
    "city_state": "",
    "floor": "5",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "102"
  },
  {
    "property_type": "Office",
    "address": "85 99 University Pl",
    "city_state": "",
    "floor": "6",
    "suite": "-",
    "use_type": "Office",
    "size_sf": "4796",
    "rent_per_sf": "",
    "page_number": "102"
  }
];
